name: shiny_base
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::r-base=4.3.2
  - conda-forge::r-tidyverse=2.0.0
  - conda-forge::r-dt=0.31
  - conda-forge::r-plotly=4.10.4
  - conda-forge::r-rsqlite=2.3.4
  - conda-forge::r-shiny=1.8.0
  - conda-forge::r-shinycssloaders=1.0.0
  - conda-forge::r-shinyjs=2.1.0
  - conda-forge::r-shinythemes=1.2.0
  - conda-forge::r-shinywidgets=0.8.1
  - conda-forge::r-bslib=0.6.1
  - conda-forge::r-colourpicker=1.3.0
  - conda-forge::r-colorspace=2.1-0
  - conda-forge::r-crosstalk=1.2.1
  - conda-forge::r-patchwork=1.2.0
  - conda-forge::r-openxlsx=4.2.5.2
  - conda-forge::r-waiter=0.2.5
