name: shiny_base
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::sqlite=3.40.0
  - conda-forge::r-base=4.2.2
  - conda-forge::r-tidyverse=1.3.2
  - conda-forge::r-dt=0.27
  - conda-forge::r-plotly=4.10.1
  - conda-forge::r-rsqlite=2.2.20
  - conda-forge::r-shiny=1.7.4
  - conda-forge::r-shinycssloaders=1.0.0
  - conda-forge::r-shinyjs=2.1.0
  - conda-forge::r-shinywidgets=0.7.6
  - conda-forge::r-bslib=0.4.2
  - conda-forge::r-colourpicker=1.2.0
  - conda-forge::r-colorspace=2.1_0
  - conda-forge::r-patchwork=1.1.2
